spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: admin
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 3333
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
user:
  test:
    property: prod-value
