spring:
  application:
    name: product-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
user:
  test:
    property: initial-value
